Repository LINKLE-2025/LINKLE_Backend, pull requests merged in 2025-09, with the labels that each got.

#1 docs: 환경변수 분리
  .gitignore
  src/main/resources/application-example.properties
  src/main/resources/application.properties
Labels: documentation

#6 fix: CORS 오류 수정
  src/main/java/com/linkle/config/CorsFilterConfig.java
  src/main/java/com/linkle/controller/SampleController.java
  src/main/resources/application-example.properties
Labels: bug, enhancement

#8 feat: profile 기본 구조 추가
  src/main/java/com/linkle/controller/UserController.java
  src/main/java/com/linkle/domain/dto/ParticipateDTO.java
  src/main/java/com/linkle/domain/dto/UserLinkerCountDTO.java
  src/main/java/com/linkle/domain/dto/UserParticipateLinkerDTO.java
  src/main/java/com/linkle/repository/ParticipateRepository.java
  src/main/java/com/linkle/service/ProfileService.java
Labels: enhancement

#9 feat: 프로필 이미지 관련 기능 1차 추가
  build.gradle
  src/main/java/com/linkle/config/MinioConfig.java
  src/main/java/com/linkle/controller/UserController.java
  src/main/java/com/linkle/service/ProfileService.java
Labels: duplicate

#11 feat: 친구 기능 추가
  src/main/java/com/linkle/controller/FriendController.java
  src/main/java/com/linkle/domain/dto/FriendDTO.java
  src/main/java/com/linkle/domain/entity/Friend.java
  src/main/java/com/linkle/domain/entity/FriendState.java
  src/main/java/com/linkle/repository/FriendRepository.java
  src/main/java/com/linkle/service/FriendService.java
  src/main/resources/application-example.properties
Labels: enhancement

#19 fix: enum 수정
  src/main/java/com/linkle/domain/entity/LinkerState.java
Labels: bug

#21 fix: profile-user 기능 분리
  src/main/java/com/linkle/controller/ProfileController.java
  src/main/java/com/linkle/domain/dto/ProfileEditRequestDTO.java
  src/main/java/com/linkle/domain/dto/ProfileEditResponseDTO.java
  src/main/java/com/linkle/domain/dto/ProfileLinkerCountDTO.java
  src/main/java/com/linkle/domain/dto/ProfileParticipateLinkerDTO.java
  src/main/java/com/linkle/repository/ParticipateRepository.java
  src/main/java/com/linkle/service/ProfileService.java
Labels: enhancement

#23 feat: Profile에서 내가 올린 Post 보기 구현
  src/main/java/com/linkle/controller/PostController.java
  src/main/java/com/linkle/controller/ProfileController.java
  src/main/java/com/linkle/domain/dto/ProfilePostDTO.java
  src/main/java/com/linkle/repository/PostRepository.java
  src/main/java/com/linkle/service/ProfileService.java
Labels: enhancement

#26 feat: 로그인 및 회원가입 도메인 추가
  build.gradle
  src/main/java/com/linkle/controller/AuthController.java
  src/main/java/com/linkle/domain/dto/DuplicationCheckResponseDTO.java
  src/main/java/com/linkle/domain/dto/EmailCheckRequestDTO.java
  src/main/java/com/linkle/domain/dto/NicknameCheckRequestDTO.java
  src/main/java/com/linkle/domain/dto/UserLoginRequestDTO.java
  src/main/java/com/linkle/domain/dto/UserLoginResponseDTO.java
  src/main/java/com/linkle/domain/dto/UserSignupRequestDTO.java
  src/main/java/com/linkle/repository/UserRepository.java
  src/main/java/com/linkle/service/AuthService.java
  src/main/java/com/linkle/service/MailService.java
  src/main/java/com/linkle/util/CodeGenerator.java
  src/main/resources/application-example.properties
Labels: enhancement

#27 feat: 회원가입 단계별 컨트롤러 구현
  src/main/java/com/linkle/config/RedisConfig.java
  src/main/java/com/linkle/controller/AuthController.java
  src/main/java/com/linkle/service/AuthMailService.java
  src/main/java/com/linkle/service/MailService.java
Labels: enhancement

#29 fix: 친구 검색 경로 수정 및 DTO 수정
  src/main/java/com/linkle/controller/SearchController.java
  src/main/java/com/linkle/domain/dto/SearchResponseDTO.java
  src/main/java/com/linkle/repository/FriendRepository.java
  src/main/java/com/linkle/repository/UserRepository.java
  src/main/java/com/linkle/service/SearchService.java
Labels: bug

#33 fix: 친구 목록 조회 수정
  src/main/java/com/linkle/repository/FriendRepository.java
Labels: bug

#34 feat: refresh token 발급 구조 완성
  src/main/java/com/linkle/config/SecurityConfig.java
  src/main/java/com/linkle/controller/AuthController.java
  src/main/java/com/linkle/domain/dto/UserLoginResponseDTO.java
  src/main/java/com/linkle/repository/RefreshTokenRepository.java
  src/main/java/com/linkle/service/AuthService.java
  src/main/java/com/linkle/util/JwtTokenProvider.java
  src/main/resources/application.properties
Labels: enhancement

#36 feat: 친구 성별 추가
  src/main/java/com/linkle/domain/dto/FriendResponseDTO.java
  src/main/java/com/linkle/repository/FriendRepository.java
Labels: enhancement

#39 feat: 로그인 구현 완료
  src/main/java/com/linkle/controller/AuthController.java
  src/main/java/com/linkle/domain/dto/UserAuthDTO.java
  src/main/java/com/linkle/service/AuthService.java
  src/main/java/com/linkle/util/JwtTokenProvider.java
Labels: enhancement

#41 feat: 비밀번호 재설정 구현
  src/main/java/com/linkle/controller/AuthController.java
  src/main/java/com/linkle/controller/CommonController.java
  src/main/java/com/linkle/domain/dto/UserPasswordResetDTO.java
  src/main/java/com/linkle/service/AuthService.java
Labels: enhancement

#50 feat: 회원 탈퇴 기능 추가
  src/main/java/com/linkle/repository/FriendRepository.java
  src/main/java/com/linkle/repository/ParticipateRepository.java
  src/main/java/com/linkle/repository/PostRepository.java
  src/main/java/com/linkle/repository/ReplyRepository.java
  src/main/java/com/linkle/service/ProfileService.java
Labels: enhancement

#58 feat: Python AI 연결 구현
  src/main/java/com/linkle/config/AppConfig.java
  src/main/java/com/linkle/controller/RecommendController.java
  src/main/java/com/linkle/domain/dto/RecommendLinkerDTO.java
  src/main/java/com/linkle/repository/ParticipateRepository.java
  src/main/java/com/linkle/service/RecommendService.java
Labels: enhancement

#67 fix: DB 테이블명 불일치 수정
  src/main/java/com/linkle/repository/ParticipateRepository.java
  src/main/resources/application-example.properties
Labels: bug, enhancement

#68 fix: 참여 내역 구조 조정
  src/main/java/com/linkle/repository/ParticipateRepository.java
Labels: enhancement

#69 changed: 형태 변환
  src/main/java/com/linkle/service/ProfileService.java
  src/main/java/com/linkle/service/RecommendService.java
  src/main/java/com/linkle/service/SearchService.java
Labels: bug

#82 feat: 기본 링커 세부사항 수정
  src/main/java/com/linkle/config/LinkerDataInitializer.java
Labels: enhancement

#87 fix: 프로필 링커 참여 통계 수정
  src/main/java/com/linkle/controller/ProfileController.java
  src/main/java/com/linkle/domain/dto/CategoryStatsDTO.java
  src/main/java/com/linkle/repository/ParticipateRepository.java
  src/main/java/com/linkle/service/ProfileService.java
Labels: bug, enhancement
